name: OctoBlog
pygments: true


authors:
  sergio:
    display_name: Sergio Marín
    title: Instructor
    gravatar: 
    #email: 
    #web: 
    twitter: highercomve
    github: highercomve
  gustavo:
    display_name: Gustavo Giménez
    title: Desarrollador
    gravatar: 
    #email: 
    #web: 
    twitter: gonzo_p
    github: gusga
  blanca:
    display_name: Blanca Pérez
    title: Instructor
    gravatar: 
    #email: 
    #web: 
    twitter: onlyblank
    github: onlyblank
  ciriaco:  
    display_name: Ramón Ciriaco
    title: Instructor
    gravatar:
    #email:
    #web:
    twitter: zamuro57
    github: zamuro57
  renier:
    display_name: Renier Chico
    title: Desarrollador
    gravatar:
    #email:
    #web:
    twitter: racs182
    github: racs182


